// Shared "master document" print template — used by Purchase Requisition,
// Purchase Order, Purchase GRN (and any future voucher print) so every
// printed document shares the same professional A4 layout: branded header,
// lettered sections, bordered tables, and a sign-off block. Modeled on the
// Work Order "Job Card" print, which is the visual quality bar for this app.

export const toNum = (v: unknown): number => Number(v ?? 0) || 0;

export const escapeHtml = (v: unknown): string =>
  String(v ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));

export const fmtMoney = (n: number): string =>
  Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export const fmtQty = (n: number): string =>
  Number(n || 0).toLocaleString("en-IN", { maximumFractionDigits: 3 });

export const PRINT_DOC_CSS = `
*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,Helvetica,sans-serif;}
body{padding:8mm 10mm;color:#000;background:#fff;font-size:8pt;}
table{width:100%;border-collapse:collapse;}
td,th{border:1px solid #999;padding:2px 4px;vertical-align:middle;color:#000;}
th{background:#efefef;font-weight:700;text-align:left;white-space:nowrap;font-size:6pt;text-transform:uppercase;}
.doc-hdr{border-collapse:collapse;margin-bottom:4px;border:2px solid #000;}
.doc-hdr td{border:none;padding:5px 8px;vertical-align:top;}
.doc-hdr .company{width:35%;border-right:1px solid #000;vertical-align:middle;}
.doc-hdr .company .name{font-size:14pt;font-weight:900;letter-spacing:.5px;line-height:1.1;}
.doc-hdr .company .tag{font-size:6.5pt;font-weight:700;margin-top:2px;}
.doc-hdr .title{width:28%;border-right:1px solid #000;text-align:center;vertical-align:middle;}
.doc-hdr .title .t{font-size:13pt;font-weight:900;letter-spacing:1px;text-transform:uppercase;line-height:1.1;}
.doc-hdr .title .s{font-size:6.5pt;color:#444;margin-top:3px;font-weight:600;}
.doc-hdr .meta{width:37%;}
.doc-hdr .meta table{border-collapse:collapse;}
.doc-hdr .meta td{border:none;padding:1px 0;font-size:7pt;}
.doc-hdr .meta td.k{font-weight:700;white-space:nowrap;padding-right:4px;}
.ph{background:#fff;color:#000;font-weight:900;font-size:7.5pt;letter-spacing:.5px;padding:2px 0;text-transform:uppercase;border-bottom:2px solid #000;margin-top:4px;margin-bottom:2px;display:block;}
.doc-table{margin-bottom:3px;}
.doc-table td.r,.doc-table th.r{text-align:right;}
.doc-table td.c,.doc-table th.c{text-align:center;}
.doc-table tfoot td{background:#efefef;font-weight:800;}
.signoff{border-top:2px solid #000;margin-top:6px;padding-top:4px;}
.signoff table{border-collapse:collapse;}
.signoff td{border:1px solid #999;text-align:center;padding:3px 6px;width:25%;}
.signoff .line{height:25px;border-bottom:1px solid #bbb;margin-bottom:3px;}
.signoff .role{font-size:7pt;font-weight:800;}
.signoff .sub{font-size:6pt;color:#555;margin-top:1px;}
.foot{font-size:6pt;color:#666;text-align:center;margin-top:3px;}
@media print{body{padding:7mm 8mm;}@page{margin:6mm;size:A4 portrait;}}
`;

export function printHeaderHtml(opts: {
  companyName: string;
  companyTag?: string;
  docTitle: string;
  docSubtitle?: string;
  meta: [string, string][];
}): string {
  const metaRows = opts.meta
    .map(([k, v]) => `<tr><td class="k">${escapeHtml(k)}</td><td>: ${escapeHtml(v)}</td></tr>`)
    .join("");
  return `
  <table class="doc-hdr">
    <tbody><tr>
      <td class="company">
        <div class="name">${escapeHtml(opts.companyName)}</div>
        <div class="tag">${escapeHtml(opts.companyTag ?? "")}</div>
      </td>
      <td class="title">
        <div class="t">${escapeHtml(opts.docTitle)}</div>
        <div class="s">${escapeHtml(opts.docSubtitle ?? "")}</div>
      </td>
      <td class="meta"><table><tbody>${metaRows}</tbody></table></td>
    </tr></tbody>
  </table>`;
}

export function sectionHtml(letter: string, label: string): string {
  return `<span class="ph">${escapeHtml(letter)} &middot; ${escapeHtml(label)}</span>`;
}

export function signOffHtml(roles: string[]): string {
  const cells = roles
    .map(role => `
      <td>
        <div class="line"></div>
        <div class="role">${escapeHtml(role)}</div>
        <div class="sub">Name / Signature / Date</div>
      </td>`)
    .join("");
  return `<div class="signoff"><table><tbody><tr>${cells}</tr></tbody></table></div>`;
}

export function footerNoteHtml(docLabel: string, companyName: string): string {
  const today = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  return `<div class="foot">Generated by AJ Shrink ERP &middot; ${escapeHtml(today)} &middot; ${escapeHtml(companyName)} &middot; This is a system generated ${escapeHtml(docLabel)}</div>`;
}

/**
 * Opens the print popup synchronously — call this FIRST, before any `await`,
 * directly inside the click handler. Browsers treat `window.open` as a blocked
 * pop-up unless it runs synchronously in response to a user gesture, so if the
 * document body needs an async fetch first, open the window immediately and
 * write the content into it once the data arrives (see writeAndPrint).
 */
export function openPrintWindow(): Window | null {
  return window.open("", "_blank", "width=1050,height=820");
}

export function writeAndPrint(win: Window, title: string, bodyHtml: string): void {
  win.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title><style>${PRINT_DOC_CSS}</style></head><body>${bodyHtml}</body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => { win.print(); }, 400);
}
