-- ═══════════════════════════════════════════════════════════════════════════
-- ArtworkSubGroupMaster — ALTER script (run after table already created)
-- Adds all ArtworkMasterMain-matching columns
-- ═══════════════════════════════════════════════════════════════════════════

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='LedgerID')
    ALTER TABLE ArtworkSubGroupMaster ADD LedgerID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='JobName')
    ALTER TABLE ArtworkSubGroupMaster ADD JobName NVARCHAR(128) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ClientArtWorkNo')
    ALTER TABLE ArtworkSubGroupMaster ADD ClientArtWorkNo NVARCHAR(128) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ArtWorkDescription')
    ALTER TABLE ArtworkSubGroupMaster ADD ArtWorkDescription NVARCHAR(512) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='DocumentType')
    ALTER TABLE ArtworkSubGroupMaster ADD DocumentType NVARCHAR(64) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='DocumentNo')
    ALTER TABLE ArtworkSubGroupMaster ADD DocumentNo NVARCHAR(64) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='DocumentDate')
    ALTER TABLE ArtworkSubGroupMaster ADD DocumentDate DATETIME NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='SalesEmployeeID')
    ALTER TABLE ArtworkSubGroupMaster ADD SalesEmployeeID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ArtworkCost')
    ALTER TABLE ArtworkSubGroupMaster ADD ArtworkCost FLOAT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ReceivedDate')
    ALTER TABLE ArtworkSubGroupMaster ADD ReceivedDate DATETIME NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ExpectedCompletionDate')
    ALTER TABLE ArtworkSubGroupMaster ADD ExpectedCompletionDate DATETIME NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='CategoryID')
    ALTER TABLE ArtworkSubGroupMaster ADD CategoryID BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='JobQty')
    ALTER TABLE ArtworkSubGroupMaster ADD JobQty BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='JobSize')
    ALTER TABLE ArtworkSubGroupMaster ADD JobSize NVARCHAR(128) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='PaperDetails')
    ALTER TABLE ArtworkSubGroupMaster ADD PaperDetails NVARCHAR(256) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='MachineName')
    ALTER TABLE ArtworkSubGroupMaster ADD MachineName NVARCHAR(128) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='DesignSide')
    ALTER TABLE ArtworkSubGroupMaster ADD DesignSide NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='TypeOfProduct')
    ALTER TABLE ArtworkSubGroupMaster ADD TypeOfProduct NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ArtworkName')
    ALTER TABLE ArtworkSubGroupMaster ADD ArtworkName NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ArtworkSubGroupMaster' AND COLUMN_NAME='ArtworkStage')
    ALTER TABLE ArtworkSubGroupMaster ADD ArtworkStage NVARCHAR(100) NULL;
GO

PRINT 'ArtworkSubGroupMaster columns updated successfully.';
GO
